language: rust
rust:
  - nightly
sudo: 9000
dist: trusty

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-6
            - clang-5.0
      env:
        global:
          - CC=gcc-6
          - CXX=g++-6
          - LIBCLANGPATH=/usr/lib/clang/5.0/lib

env:
  - FEATURES=""
  - FEATURES="--features debugmozjs"

script:
  - cargo build --verbose --verbose $FEATURES

before_install:
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install yasm; fi

notifications:
  webhooks: http://build.servo.org:54856/travis
