[package]
name = "mozjs_sys"
description = "System crate for the Mozilla SpiderMonkey JavaScript engine."
repository = "https://github.com/servo/mozjs/"
version = "0.50.0"
authors = ["Mozilla"]
links = "mozjs"
build = "build.rs"
license = "MPL-2.0"
exclude = [
  "mozjs/js/src/tests/**",
  "mozjs/js/src/octane/**",
  "mozjs/js/src/jit-test/**",
  "mozjs/js/src/jsapi-tests/**",
  "mozjs/js/src/doc/**",
]

[features]
debugmozjs = []
promises = []

[lib]
name = "mozjs_sys"
path = "lib.rs"

[build-dependencies]
num_cpus = "1.1.0"

[dependencies]
libc = "0.2"
libz-sys = "1.0"
